// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjE-DhtwHd3HrtAbVpL52JV77ejHF2nW8',
    appId: '1:392561384256:web:509625ed2969d43d2cb8a5',
    messagingSenderId: '392561384256',
    projectId: 'flutterapplication2-b04db',
    authDomain: 'flutterapplication2-b04db.firebaseapp.com',
    storageBucket: 'flutterapplication2-b04db.firebasestorage.app',
    measurementId: 'G-XZDKB9XFHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKY2P6YNsqa7KcwbvboIDiEdQUYizl8k',
    appId: '1:392561384256:android:4b07b0708f2103ba2cb8a5',
    messagingSenderId: '392561384256',
    projectId: 'flutterapplication2-b04db',
    storageBucket: 'flutterapplication2-b04db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjE-DhtwHd3HrtAbVpL52JV77ejHF2nW8',
    appId: '1:392561384256:web:3d83cbb2a66b7ab82cb8a5',
    messagingSenderId: '392561384256',
    projectId: 'flutterapplication2-b04db',
    authDomain: 'flutterapplication2-b04db.firebaseapp.com',
    storageBucket: 'flutterapplication2-b04db.firebasestorage.app',
    measurementId: 'G-Q5J56FSCHD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmBjh00CEhBkYm1TDcPdhXcPuyJGRoLYM',
    appId: '1:392561384256:ios:b3c5e47895913b912cb8a5',
    messagingSenderId: '392561384256',
    projectId: 'flutterapplication2-b04db',
    storageBucket: 'flutterapplication2-b04db.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmBjh00CEhBkYm1TDcPdhXcPuyJGRoLYM',
    appId: '1:392561384256:ios:b3c5e47895913b912cb8a5',
    messagingSenderId: '392561384256',
    projectId: 'flutterapplication2-b04db',
    storageBucket: 'flutterapplication2-b04db.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

}